version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pygments
    versions:
    - 2.8.0
  - dependency-name: ipython
    versions:
    - 7.20.0
  - dependency-name: pandas
    versions:
    - 1.2.1
  - dependency-name: pyyaml
    versions:
    - 5.4.1
  - dependency-name: scikit-learn
    versions:
    - 0.24.1
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
  - dependency-name: pygithub
    versions:
    - 1.54.1
