name: language-dataset-ci
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  lint-black:
    name: lint (black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.x'
          architecture: 'x64'
      - run: pip install black
      - run: black --check tools/
  lint-data:
    name: lint (data)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.x'
          architecture: 'x64'
      - run: pip install poetry
      - run: sudo apt install libyaml-dev
      - run: poetry install --no-dev
      - run: poetry run python -m tools.lint
  check-commit:
    name: check no pending changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.x'
          architecture: 'x64'
      - run: pip install poetry
      - run: sudo apt install libyaml-dev
      - run: poetry install --no-dev
      - run: poetry run python -m tools.prepare_commit
      - run: git diff --exit-code
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.x'
          architecture: 'x64'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4.x'
      - run: sudo apt update
      - run: sudo apt install libyaml-dev cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev
      - run: gem install --no-rdoc --no-ri github-linguist
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest tools
